version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  groups:
    dev-dependencies:
      patterns:
        - "*"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  groups:
    dev-dependencies:
      patterns:
        - "*"
